### ISSUE TITLE
auto-connect to rethinkdb

### ISSUE THREAD

**Issue by mohit5540** [grantcarthew/node-rethinkdb-job-queue#85] opened 2018-08-13 09:38 UTC
@grantcarthew : 

How can we auto connect rethinkdb-jobqueue to rethinkdb ?

For example, rethinkdb-jobqueue connects to rethink db when we run(start) the script. While the script is continuously running, if rethinkdb goes down in between, the worker doesnt get connect with rethinkdb. We need to restart the script in order to get it connect with rethink db.
 
So is there any workaround on this to connect rethink db without restarting the script.

Regards

**Comment by grantcarthew** [comment] 2018-08-13 22:02
Hi @mohit5540,

This is a duplicate of #77 

I'm not working on the queue at the moment however if you wish to send a PR I'll be happy to work with you.

Thanks.

**Closed as completed by grantcarthew** 2018-08-13 22:02 UTC
